src/objects/Answer__c.object
<CustomObject>
    <fields>
        <fullName>QuestionResource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QuestionResource</label>
        <referenceTo>QuestionResource__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <label>Answer Text</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>CorrectAnswer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CorrectAnswer</label>
        <referenceTo>Answer__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>CorrectAnswers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Text</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QuestionResource__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>QuestionResources</relationshipLabel>
        <relationshipName>QuestionResources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>QuestionResource</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>QuestionResource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuestionResources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QuestionsAndAnswersRest.cls
@RestResource(urlMapping='/Question/*')
global with sharing class QuestionsAndAnswersRest {

    @HttpGet
    global static String getAllQuestionsAndAnswers(){

        List<Question__c> questions = [SELECT Id, Language__c, Name, CorrectAnswer__c  From Question__c];

        List<QuestionResource__c> questionResources = [SELECT Id, Question__r.Language__c, Question__r.Name, Question__r.CorrectAnswer__c, (SELECT Name FROM Answers__r)  From QuestionResource__c WHERE Question__c IN ( SELECT Id FROM Question__c  )];
        Map<String, QuestionResource__c> questionMap = new Map<String, QuestionResource__c>(questionResources);


        return JSON.serializePretty(questionMap);

    }

}